# Site settings
title: Meu blog pessoal
description: Um blog sobre pessoas e tecnologia
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://caio.ninja" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Caio Incau
user_description: Front-End Engineer at @moip, Slytherin, JS lover and Batman fan.
user_title: Front-End Engineer at @moip, Slytherin, JS lover and Batman fan.
email: caioincau@gmail.com
twitter_username: icaioincau
github_username:  caioincau
gplus_username:  +CaioIncau
disqus_username: CaioIncau

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
include: ['_headers']