version: 2
jobs:
  deploy:
    docker:
      - image: circleci/ruby:2.4.3-node-browsers
    working_directory: ~/caioincau.github.io
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SO:ME:FIN:G:ER:PR:IN:T"
      - checkout
      - run: npm install
      - run: gem install bundler jekyll
      - run: jekyll build
      - run: git config --global user.email "caioincau@gmail.com"
      - run: git config --global user.name "Caio Incau"
      - run: git config --global push.default matching
      - run: git commit -am "[ci skip] new build"
      - run: git push
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'develop' ]; then
              bash .circleci/setup-github.sh
            fi
workflows:
  version: 2
  build:
    jobs:
      - deploy